# Base image
FROM python:3.10-alpine

# Ignore interactive prompts during the build process
ENV DEBIAN_FRONTEND=noninteractive

# Install the necessary tools and dependencies
RUN apk add --no-cache \
    curl \
    build-base \
    protobuf \
    protobuf-dev

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Configure the Cargo mirror source
RUN mkdir -p ~/.cargo \
    && echo '[source.crates-io]' >> ~/.cargo/config.toml \
    && echo 'replace-with = "ustc"' >> ~/.cargo/config.toml \
    && echo '[source.ustc]' >> ~/.cargo/config.toml \
    && echo 'registry = "https://mirrors.ustc.edu.cn/crates.io-index"' >> ~/.cargo/config.toml

# Install maturin
RUN pip3 install maturin

# Set the working directory
WORKDIR /app